ci:
  script:
  - chmod -R 777 storage
  - composer install
  - npm install
  - gulp bower
  - gulp build
  - gulp deploy
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan migrate --database=testing
  - php artisan db:seed --database=testing --class=installerSeeder
  - bin/codecept run --env=core -g migration
  - bin/codecept run --env=installer
  - bin/codecept run
