ci:
  script:
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - composer install
  - npm install
  - gulp bower
  - gulp build
  - gulp deploy
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
#  - php artisan codeception:dbdump testing --dump tests/_data/empty.sql --empty-database --no-seeding
#  - php artisan codeception:dbdump testing --dump tests/_data/testing.sql --empty-database --seeder-class TestingSeeder
#  - bin/phpcpd modules/Dashboard
#  - bin/phpcpd modules/Files
#  - bin/phpcpd modules/Installer
#  - bin/phpcpd modules/Pages
#  - bin/phpcpd modules/Posts
#  - bin/phpcpd modules/Themes
#  - bin/phpcpd modules/Users
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ core
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Dashboard
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Files
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Installer
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Pages
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Posts
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Themes
#  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ module/Users
  - bin/codecept run --env=core -g migration --coverage --coverage-xml
  - bin/codecept run --env=installer --coverage --coverage-xml
  - bin/codecept run --coverage --coverage-xml
