ci:
  script:
  - chmod -R 777 storage
  - composer install
  - npm install
  - gulp bower
  - gulp build
  - gulp deploy
  - php artisan theme:publish
  - php artisan module:publish
  - bin/codecept run --env=core
  - bin/codecept run --env=installer
  - bin/codecept run
