ci:
  script:
  - chmod -R 777 storage
  - composer install
  - npm install
  - gulp bower
  - gulp build
  - gulp deploy
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan codeception:dbdump testing --dump tests/_data/empty.sql --empty-database --no-seed
  - php artisan codeception:dbdump testing --dump tests/_data/installer.sql --empty-database
  - php artisan codeception:dbdump testing --dump tests/_data/testing.sql --empty-database --seed-class TestingSeeder
  - bin/codecept run --env=core -g migration
  - bin/codecept run --env=installer
  - bin/codecept run
