stages:
  - build
  - test

job_build:
  stage: build
  only:
  - master
  - staging
  - development
  script:
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - composer install
  - cd resources/themes/adminlte/assets && npm install && gulp sass && cd -
  - cd resources/themes/lumen/assets && npm install && gulp bower && cd -
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
  - php artisan codeception:dbdump testing --dump tests/_data/empty.sql --empty-database --no-seeding
  - php artisan codeception:dbdump testing --dump tests/_data/testing.sql --empty-database --seeder-class TestingSeeder
  tags:
  - php7
  - nodejs
  - composer
  - linux

job_tests_linux: # Run tests suites
  stage: test
  only:
  - master
  - staging
  - development
  before_script:
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - composer install
  - cd resources/themes/adminlte/assets && npm install && gulp sass && cd -
  - cd resources/themes/lumen/assets && npm install && gulp bower && cd -
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
  script:
  - bin/codecept run -g core api
  - bin/codecept run --env=installer -g installer api
  - bin/codecept run -g installed api
  - bin/codecept run -g core functional --coverage
  - bin/codecept run --env=installer -g installer functional --coverage
  - bin/codecept run -g installed functional --coverage
  - bin/codecept run -g core unit --coverage
  - bin/codecept run --env=installer -g installer unit --coverage #
  - bin/codecept run -g installed unit --coverage
  - bin/codecept run -g core acceptance #
  - bin/codecept run --env=installer -g installer acceptance #
  - bin/codecept run -g installed acceptance #
  when: on_success
  tags:
  - php7
  - nodejs
  - composer
  - mysql
  - linux

job_tests_windows: # Run tests suites
  stage: test
  only:
  - staging
  - development
  before_script:
  - git config --global url."https://gitlab.com/".insteadOf "git@gitlab.com:"
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - composer install
  - cd resources\themes\adminlte\assets && npm install && gulp sass && cd -
  - cd resources\themes\lumen\assets && npm install && gulp bower && cd -
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
  script:
  - bin\codecept run --env=firefox -g core acceptance #
  - bin\codecept run --env=installer,firefox -g installer acceptance #
  - bin\codecept run --env=firefox -g installed acceptance #
  #- bin\codecept run --env=ie -g core acceptance #
  #- bin\codecept run --env=installer,ie -g installer acceptance #
  #- bin\codecept run --env=ie -g installed acceptance #
  when: on_success
  tags:
  - php7
  - nodejs
  - composer
  - mysql
  - windows

job_cs: # CodeStyle
  stage: test
  only:
  - development
  before_script:
  - composer install
  script:
  - bin/phpcs --standard=$PWD/vendor/pragmarx/laravelcs/Standards/Laravel/ core
  when: always
  tags:
  - php7
  - composer
  - linux

job_cs_duplicated: # CodeStyle - Looking for duplicated code
  stage: test
  only:
  - development
  before_script:
  - composer install
  script:
  - bin/phpcpd core
  when: always
  tags:
  - php7
  - composer
  - linux
