language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - composer install
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration

script:
  - bin/codecept run --env=core -g migration
  - bin/codecept run --env=installer
  - bin/codecept run
