language: php

php:
  - 7

before_script:
  - mysql -e 'CREATE DATABASE cvepdb_cms_testing;'
  - mkdir -p storage/app
  - mkdir -p storage/logs
  - mkdir -p storage/framework/cache
  - mkdir -p storage/framework/sessions
  - mkdir -p storage/framework/views
  - chmod -R 777 storage
  - php -r "file_exists('.env.installer') || copy('.env.example', '.env.installer');"
  - composer install --prefer-dist --no-interaction --optimize-autoloader
  - cd resources/themes/adminlte/assets && npm install && gulp sass && cd -
  - cd resources/themes/lumen/assets && npm install && gulp bower && cd -
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
  - echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - bin/codecept run -g core api
  - bin/codecept run --env=installer -g installer api
  - bin/codecept run -g installed api
  - bin/codecept run -g core functional --coverage
  - bin/codecept run --env=installer -g installer functional --coverage
  - bin/codecept run -g installed functional --coverage
  - bin/codecept run -g core unit --coverage
  - bin/codecept run --env=installer -g installer unit --coverage
  - bin/codecept run -g installed unit --coverage
  - bin/codecept run -g core acceptance
  - bin/codecept run --env=installer -g installer acceptance
  - bin/codecept run -g installed acceptance
