language: php

php:
  - 5.6
  - 7

before_script:
  - chmod -R 777 storage
  - chmod -R 777 public/uploads
  - ssh -o "StrictHostKeyChecking no" gitlab.com
  - composer install --prefer-source --no-interaction --optimize-autoloader
  - php artisan theme:publish
  - php artisan module:publish
  - php artisan module:publish-migration
  - echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - bin/codecept run --env=core -g migration
  - bin/codecept run --env=installer
  - bin/codecept run
